server:
  port: @server.port@
spring:
  application:
    name: @project.name@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
  flyway:
    schemas: nw

  kafka:
    bootstrap-servers: kenny-kafka1.bst1.rbkmoney.net:9092
#    ssl:
#      trust-store-location: "classpath:cert/truststore.p12"
#      trust-store-password: "kenny12"
#      key-store-location: "classpath:cert/kenny-k.struzhkin.p12"
#      key-store-password: "kenny"
#      key-password: "kenny"
#      key-store-type: PKCS12
#      trust-store-type: PKCS12
    consumer:
      group-id: "TestListener"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.rbkmoney.newway.serde.SinkEventDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      client-id: test
    listener:
      type: batch
      ack-mode: manual
      concurrency: 1
      poll-timeout: 1000 #ms
      no-poll-threshold: 5.0 # * poll-timeout value = when consumer is dead
      log-container-config: true
      monitor-interval: 10s
    client-id: test
    properties:
      security:
        protocol: PLAINTEXT

management:
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
retry-policy:
  maxAttempts: 10

invoicing:
  kafka.topic: mg-invoice-100-2

bm:
  partyManagement:
    url: http://bustermaze:8022/repo
    polling:
      delay: 10000
      retryDelay: 1000
      maxPoolSize: 1
      maxQuerySize: 300
  payout:
    url: http://bustermaze:8022/repo/payout
    polling:
      delay: 10000
      retryDelay: 1000
      maxPoolSize: 1
  pollingEnabled: true
identity:
  polling:
    url: http://wapi:8022/v1/eventsink/identity
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
wallet:
  polling:
    url: http://wapi:8022/v1/eventsink/wallet
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
source:
  polling:
    url: http://wapi:8022/v1/eventsink/source
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
destination:
  polling:
    url: http://wapi:8022/v1/eventsink/destination
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
deposit:
  polling:
    url: http://wapi:8022/v1/eventsink/deposit
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
withdrawal:
  polling:
    url: http://wapi:8022/v1/eventsink/withdrawal
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
rate:
  polling:
    url: http://xrates:8022/v1/event_sink
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
withdrawal_session:
  polling:
    url: http://wapi:8022/v1/eventsink/withdrawal_session
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
dmt:
  url: http://dominant:8022/v1/domain/repository
  networkTimeout: 5000
  polling:
    delay: 3000
    maxQuerySize: 10
    enable: true
